### ISSUE TITLE
windows not equalized when using diffview.nvim

### ISSUE THREAD

**Issue by willnorris** [nvim-focus/focus.nvim#100]
@beauwilliams, do you recall why you got rid of the `vim.schedule` in https://github.com/beauwilliams/focus.nvim/commit/6ff7636a6ab7603ec39abe921ad62d406fd7dfa2#diff-5a789a756398152dea16e4dfefb3ca2ca53fd37fd12c87cfd1329b863ce2f6e1R43-R44 ?

That seems to be the change that is preventing the resize() event from getting called at the right time in diffview.nvim.  Right now, the windows are staying sized unevenly.  Swapping those two lines so that vim.schedule is used again cases it behave correctly, and for diffview windows to alway be equalized.

I'm also not sure if this may have regressed #50 , which seems to be the motivation for adding the `vim.schedule` call in the first place?  I'm happy to send a PR, but wanted to check if there was a specific reason for removing it... perhaps it was causing some other issues?

**Comment by cryptomilk** [comment]
Please try https://github.com/nvim-focus/focus.nvim/tree/refactor.

Take a look at the **Disabling Focus** section:
https://github.com/nvim-focus/focus.nvim/tree/refactor#disabling-focus

**Comment by cryptomilk** [comment]
Fixed in current master/main.
