### ISSUE TITLE
Autoresize set to false is not working.

### ISSUE THREAD

**Issue by ilias777** [nvim-focus/focus.nvim#111]
Hi and first of all thank you for the amazing plugin.

With the new update the autoresize option does't do anything.
In the settings i have set `autoresize = { { enable = false} }` and it doesn't work.

https://github.com/nvim-focus/focus.nvim/assets/39212564/8b3d0249-d8e7-42e7-842b-176d96dcde58

Because of this, the ignored filetypes, like nvim-tree or trouble.nvim are't ignored by focus.

https://github.com/nvim-focus/focus.nvim/assets/39212564/481e4269-cc8f-4537-8e53-10763617d71f

Here is my configuration:

```lua
return {
    'nvim-focus/focus.nvim',
    enabled = true,
    event = 'VeryLazy',
    version = '*',
    keys = {
        { '<space>h', '<cmd>FocusSplitLeft<CR>', desc = 'Focus Split Left' },
        { '<space>j', '<cmd>FocusSplitDown<CR>', desc = 'Focus Split Down' },
        { '<space>k', '<cmd>FocusSplitUp<CR>', desc = 'Focus Split Up' },
        { '<space>l', '<cmd>FocusSplitRight<CR>', desc = 'Focus Split Right' },
        { '<space>m', '<cmd>FocusMaxOrEqual<CR>', desc = 'Maximaze or Equalises Split' },
    },
    config = function()
        require('focus').setup({
            autoresize = {
                enable = false,
            },
            ui = {
                number = false,
                relativenumber = false,
                hybridnumber = false,
                signcolumn = false,
            },
            -- excluded_filetypes = {
            --     'toggleterm',
            --     'qf',
            --     'help',
            --     'NvimTree',
            --     'Trouble',
            --     'tsplayground',
            --     'Outline',
            -- },
        })

        -- Ignore filetypes
        local ignore_filetypes = {
            'toggleterm',
            'qf',
            'help',
            'NvimTree',
            'Trouble',
            'tsplayground',
            'Outline',
        }
        -- Ignore buftypes
        local ignore_buftypes = {
            'nofile',
            'prompt',
            'popup',
        }

        local augroup = vim.api.nvim_create_augroup('FocusDisable', { clear = true })
        vim.api.nvim_create_autocmd('WinEnter', {
            group = augroup,
            callback = function(_)
                if vim.tbl_contains(ignore_buftypes, vim.bo.buftype) then
                    vim.b.focus_disable = true
                end
            end,
            desc = 'Disable focus autoresize for BufType',
        })

        vim.api.nvim_create_autocmd('FileType', {
            group = augroup,
            callback = function(_)
                if vim.tbl_contains(ignore_filetypes, vim.bo.filetype) then
                    vim.b.focus_disable = true
                end
            end,
            desc = 'Disable focus autoresize for FileType',
        })
    end,
}
```
My plugin manager is lazy.nvim.

The `excluded_filetype` option like before this update, was in my opinion much cleaner. It would be nice if you bring it back. 🙂

Thank you again.

**Comment by erancx** [comment]
can confirm this happens to me too.

**Comment by cryptomilk** [comment]
I wrote a test and can reproduce it. Haven't found the issue yet.

**Comment by willothy** [comment]
> The `excluded_filetype` option like before this update, was in my opinion much cleaner. It would be nice if you bring it back. 🙂

I agree with this. An autocmd works as well, but the disabled ft config option is very convenient for users.

**Comment by cryptomilk** [comment]
I found one issue, but test still fails:

WIP https://github.com/cryptomilk/focus.nvim/tree/asn-fix

**Comment by loqusion** [comment]
Should be fixed in #112

**Comment by jensenojs** [comment]
What I want to ask may not have anything to do with this issue, After I used ["Disabling Focus"](https://github.com/nvim-focus/focus.nvim#disabling-focus) in README.md,

```lua
local ignore_filetypes = { 'NvimTree' }

...

return {
    'nvim-focus/focus.nvim',
    config = function()
        require'focus'.setup({
            excluded_filetypes = {"NvimTree"}
        })
    end
}
```

NvimTree will open by autocmd after I open nvim, with focus size

<img width="1397" alt="image" src="https://github.com/nvim-focus/focus.nvim/assets/56761542/4218d3a8-f36e-4f3a-b4c4-771957c785a1">

It's the default scale but what I want is origin size when i have not met focus.nvim.

<img width="1397" alt="image" src="https://github.com/nvim-focus/focus.nvim/assets/56761542/012514ae-38a9-4483-bec5-f2b9a83b3834">

After using "Disabling Focus", reopening Nvimtree became right! No matter how i switch, it is the right size.

I want to know if there is a way to make it the original size when it enters nvim? Although it's fine now：

**Comment by willothy** [comment]
@jensenojs there was a significant refactor with some breaking changes in #106, and disabled filetypes are not built into the plugin anymore. You should use a `FileType` autocmd for that for now.

**Comment by cryptomilk** [comment]
See https://github.com/nvim-focus/focus.nvim#disabling-focus

**Comment by jensenojs** [comment]
Sorry for not being clear, I have already used the autocommand in README.md,

<img width="1173" alt="image" src="https://github.com/nvim-focus/focus.nvim/assets/56761542/52a77954-739b-41df-ae30-a3d77be935f8">

and I noticed that there was a issue about NvimTree, https://github.com/nvim-focus/focus.nvim/issues/51 , （should be NvimTree_* instead of NvimTree at that time）, but I tried with both found that now still should be NvimTree, otherwise disabling-focus won't work

> @jensenojs there was a significant refactor with some breaking changes in #106, and disabled filetypes are not built into the plugin anymore. You should use a `FileType` autocmd for that for now.

**Comment by maxfl** [comment]
I've looked at https://github.com/nvim-focus/focus.nvim/blob/a994282f957840ee3419ad62a36be9d4e155560c/lua/focus/modules/resizer.lua#L25 and I've got an impression that the conditions are swapped: in the case `utils.is_disabled()` the function is working. By setting `autoresize = { enable = true }` I was able to disable the autoresize feature.

**Comment by willothy** [comment]
Gotcha, sorry for the confusion. I'll look into this today.
