### ISSUE TITLE
[Feature/Fix] Check window layout to determine if neighboring windows can be resized

### ISSUE THREAD

**Issue by willothy** [nvim-focus/focus.nvim#114]
For plugins such as dap-ui, creating an autocmd disabling resize is not enough for focus to avoid resizing windows. After toggling dap ui, the created windows will sometimes be very small due to focus resizing the "main" window. 

As a fix for this, I think filetype and buftype checks should be reincorporated into the plugin, and the current window's neighbors (from `vim.fn.winlayout`) should be checked prior to resize to determine the bounds of the focused window.

I'll get started on a PR for this soon, just submitting this as a known issue marker.

**Comment by cryptomilk** [comment]
The thing is that you would need tons of special handling code for all the plugins out there. I don't think this is the right solution. Disabling focus globally while in dap-ui would be the right thing to do.

**Comment by willothy** [comment]
Just tested, #136 fixes the issue with dap-ui so definitely will close this issue.
