### ISSUE TITLE
Maximize seems to be broken

### ISSUE THREAD

**Issue by eddyekofo94** [nvim-focus/focus.nvim#122]
``` lua
function M.maximise()
    local width, height = vim.o.columns, vim.o.lines

    local win = vim.api.nvim_get_current_win()
    local view = vim.fn.winsaveview()
    vim.api.nvim_win_set_width(win, width)
    vim.api.nvim_win_set_height(win, height)
    vim.api.nvim_win_call(function()
        vim.fn.winrestview(view)
    end)
end
```

This method since the last updated it is broken. 
Locally I fixed it by passing the `win` variable like this
``` lua
vim.api.nvim_win_call(win, function()
        vim.fn.winrestview(view)
 end)
```

**Comment by cryptomilk** [comment]
@willothy FYI ;-)

**Comment by willothy** [comment]
Oops, that must have happened while resolving a conflict during rebase while I was cleaning up the commits in that PR. I'll send in a PR fixing this tonight!

**Comment by eddyekofo94** [comment]
There seems to be a few things not working quite right since the last refactoring. Is there tests to check nothing breaks?
