### ISSUE TITLE
cmdheight seems to be set incorrectly

### ISSUE THREAD

**Issue by qixiao986** [nvim-focus/focus.nvim#131]
after I enable focus.nvim, cmdheight=14. disable focus.nvim, cmdheight=2(which is expected)

![output](https://github.com/nvim-focus/focus.nvim/assets/3962171/13412a46-0ab0-4005-b8ac-f2c589255afb)

**Comment by sontungexpt** [comment]
![image](https://github.com/nvim-focus/focus.nvim/assets/92097639/e68970c6-8ca2-4423-ba14-025508582b67)
I also have the same problem

**Comment by cryptomilk** [comment]
This only happens if `cmdheight` is set to a  value >= 2.

@willothy

**Comment by sontungexpt** [comment]
> This only happens if `cmdheight` is set to a value >= 2.
> 
> @willothy I set it to 1, but it still happens

**Comment by willothy** [comment]
Ah, I see, I wasn't experiencing this because I use noice.nvim. Will fix today.

**Comment by willothy** [comment]
The issue was that nvim_win_set_height will change `cmdheight` if there is only one row in the layout and it is set to a height smaller than the available size. This is pretty weird and I'm not sure why nvim does it, but worked around it in #132 by checking cmdheight.
