### ISSUE TITLE
cursorline issue

### ISSUE THREAD

**Issue by dungle-scrubs** [nvim-focus/focus.nvim#152]
setting `cursorline = true` doesn't display the cursorline in the focused window only, but rather, it shows a cursorline that spans all vertically split panes.

**Comment by cryptomilk** [comment]
Works for me!

Please provide a minimal reproducer:
* https://github.com/nvim-focus/focus.nvim/tree/master/extras

**Comment by dungle-scrubs** [comment]
Thanks, that helped me narrow it down to my terminal configuration.

**Comment by dungle-scrubs** [comment]
closing
