### ISSUE TITLE
there isn't a stable branch??

### ISSUE THREAD

**Issue by ingenarel** [nvim-focus/focus.nvim#160]
this is what vim-plug is giving me
```
x focus.nvim:
    fatal: invalid reference: stable
```

and also:
![image](https://github.com/user-attachments/assets/9d548551-b796-4a99-8b6e-ded3115ed443)

**Comment by cryptomilk** [comment]
There are tags! As you are on neovim, maybe switch to a neovim plugin manager like lazy.nvim :-)

**Comment by ingenarel** [comment]
created a pull request with the readme fix
