### ISSUE TITLE
Current line is changed when creating a new vertical split

### ISSUE THREAD

**Issue by s1n7ax** [nvim-focus/focus.nvim#163]
I've been using focus.nvim for hell of a long time. I noticed it's changing current line when using `vsp`. Only recently I figured that it's this plugin causing it. here is a video.

https://github.com/user-attachments/assets/afad5915-12e1-4005-bf4d-1c447af6ab17

**Comment by cryptomilk** [comment]
See the Note at the end the Configuration section: of https://github.com/nvim-focus/focus.nvim?tab=readme-ov-file#configuration
