### ISSUE TITLE
Doesn't work with lazy.nvim

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-focus/focus.nvim#165]
The plugin is not loaded, even with "lazy = false"

![image](https://github.com/user-attachments/assets/fcc32390-0f1b-458b-991f-d125e1b88698)
![image](https://github.com/user-attachments/assets/924a9c91-cc7d-42a2-92fd-ffdb8a7eb02a)
![image](https://github.com/user-attachments/assets/f4fe193d-e1e0-446b-a3c4-4ba1da043a43)

**Comment by cryptomilk** [comment]
Thank you very much for taking the time to report a but.

However it works just fine for me. Please provide a minimal reproducer. See details at:

https://github.com/nvim-focus/focus.nvim/tree/master/extras

**Comment by YodaEmbedding** [comment]
Works fine for me.

```lua
return {
  "nvim-focus/focus.nvim",

  config = function()
    require("focus").setup {

    }
  end,
}
```
