### ISSUE TITLE
undotree autoresizes even after putting it in the ignore file types.

### ISSUE THREAD

**Issue by ingenarel** [nvim-focus/focus.nvim#166]
here's my config:
```lua
require("focus").setup{
    autoresize = {
        minwidth = 10,
        minheight = 10,
    },
}

local ignore_filetypes = {"undotree"}
local ignore_buftypes = {"nofile", "prompt", "popup"}

local augroup =
    vim.api.nvim_create_augroup("FocusDisable", { clear = true })

vim.api.nvim_create_autocmd("WinEnter", {
    group = augroup,
    callback = function(_)
        if vim.tbl_contains(ignore_buftypes, vim.bo.buftype)
        then
            vim.w.focus_disable = true
        else
            vim.w.focus_disable = false
        end
    end,
    desc = "Disable focus autoresize for BufType",
})

vim.api.nvim_create_autocmd("FileType", {
    group = augroup,
    callback = function(_)
        if vim.tbl_contains(ignore_filetypes, vim.bo.filetype) then
            vim.b.focus_disable = true
        else
            vim.b.focus_disable = false
        end
    end,
    desc = "Disable focus autoresize for FileType",
})
```
here's with the focus plugin disabled:
![sdfsdafasfsd](https://github.com/user-attachments/assets/d0c5a89f-5711-46e4-a991-d344b05e84aa)
here's with the focus plugin enabled:
![afsdafadsfdsafsdfsdafsadff](https://github.com/user-attachments/assets/ead95f97-3f86-4965-85df-20655e648e1a)

but it stops resizing the stuff after i open undo tree, so if i move to the other buffer, it's still the same size.

**Comment by cryptomilk** [comment]
The problem is that undotree calls `:vnew`, so it first splits and then later sets the filetype. Focus already did its work, before the filetype was set.

If you write this in lua, you can already pass all that to the function which creates a window.

Alternative: https://github.com/debugloop/telescope-undo.nvim

**Comment by ingenarel** [comment]
i didn't know about the telescope plugin, i'll switch to it. thanks!
