### ISSUE TITLE
Disable on floating

### ISSUE THREAD

**Issue by Davincible** [nvim-focus/focus.nvim#95]
Really nice plugin. I would like to disable it for all floating windows. Is there any way I can achieve this?

E.g. I don't want to disable it for all terminals, just for floating terms.

**Comment by cryptomilk** [comment]
Please try https://github.com/nvim-focus/focus.nvim/tree/refactor

Take a look at the **Disabling Focus** section:
https://github.com/nvim-focus/focus.nvim/tree/refactor#disabling-focus

**Comment by cryptomilk** [comment]
Fixed in current master/main.
