### ISSUE TITLE
Attempt to call nil value

### ISSUE THREAD

**Issue by CatKev** [nvim-focus/focus.nvim#96]
<img width="817" alt="Screenshot 2022-12-29 at 08 15 28" src="https://user-images.githubusercontent.com/63967960/209887461-41672882-1483-4c29-a8d3-7b62daa10b4c.png">
<img width="941" alt="Screenshot 2022-12-29 at 08 15 46" src="https://user-images.githubusercontent.com/63967960/209887492-c5fe0321-afea-42c0-966b-e836419e16cd.png">

**Comment by cryptomilk** [comment]
Please try https://github.com/nvim-focus/focus.nvim/tree/refactor

Take a look at the **Disabling Focus** section:
https://github.com/nvim-focus/focus.nvim/tree/refactor#disabling-focus

If you still see this issue, give proper instruction how to reproduce it.

**Comment by cryptomilk** [comment]
Fixed in current master/main.
