### ISSUE TITLE
Session load failure

### ISSUE THREAD

**Issue by ray-x** [nvim-focus/focus.nvim#97]
I use this plugin with a session manager 
I found the plugin will set
`		vim.o.winwidth = 1
`
This will cause an error as winwidth is smaller than minium winwidth. (winminwidth)
Why the number is set to 1? could you set it to a value no less than `winminwidth` ? thanks!

**Comment by cryptomilk** [comment]
Can you please try the https://github.com/nvim-focus/focus.nvim/tree/refactor branch?

**Comment by cryptomilk** [comment]
Note the config of the refactor branch has changed, so you need to adjust the config!

**Comment by piersolenski** [comment]
It seems to have the same issue! 🫠

**Comment by cryptomilk** [comment]
Fixed in current master/main.

**Comment by Martin1887** [comment]
I'm facing this problem with persisted.nvim. The most noticeable result is the bufferline of https://github.com/romgrk/barbar.nvim is not visible, and in a rare time it was visible but the active buffer was not detected even after moving to another buffer.

Thanks!
